name: Frontend

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  REPO_PATH: "./frontend"
  NODE_VERSION: "18.x"
  MANAGER: "npm"
  COMMAND: "ci"
  RUNNER: "npx --no-install"

on:
  push:
    branches:
      - main
    # paths:
    #   - './frontend/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}

      - name: Install dependencies
        working-directory: ${{ env.REPO_PATH }}
        run: ${{ env.MANAGER }} ${{ env.COMMAND }}

      - name: Build with Next.js
        working-directory: ${{ env.REPO_PATH }}
        run: ${{ env.RUNNER }} next build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: ./frontend/out

  Deploy-Production:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        working-directory: ${{ env.REPO_PATH }}
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        working-directory: ${{ env.REPO_PATH }}
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: ${{ env.REPO_PATH }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        working-directory: ${{ env.REPO_PATH }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}